- src/auth/login.js
- src/db/mongo.js
- src/route/auth.replace.js
- src/route/logininfo.js
#13 
로그아웃 부분 완성했고 Setting 페이지에 띄울 닉네임 속성을 추가했습니다.
> #13 edit routes for the setting page

- src/route/users.js
> Fix cases for users created before #26

- src/db/mongo.js
- src/route/auth.js
- src/route/auth.replace.js
- src/route/docs/logininfo.md
- src/route/docs/users.md
> #33 Get user's KAIST student id on signup

- src/route/auth.replace.js
- src/route/logininfo.js
> 35 add tos email on logininfo detail

- src/route/docs/users.md
- src/route/users.js
resolves #36 
- 로그인 체크 및 사용자 id 확인을 authMiddleware 미들웨어에서 수행하기 때문에, url에서 불필요한 id parameter를 제거하였습니다.
```
- "/:user_id/editNickname" → "/editNickname"
- "/:user_id/uploadProfileImage" → "/uploadProfileImage"
```
> 36 simplify users api

- .github/ISSUE_TEMPLATE/bug-report-template.md
- .github/ISSUE_TEMPLATE/issue-template.md
- .github/issue_template.md
- .github/pull_request_template.md
It closes #44 
- Images are not needed for this issue.
- 잘 사용하기 ㅎㅎ
> #44 add issue and PR template

- .prettierignore
- .prettierrc.json
It closes #48 
일관성 있는 포맷팅을 위해 prettier 설정 파일들을 추가했습니다.
- No screenshot is required for this pull request.
- 없음.
> Add prettier config

- src/route/docs/rooms.md
- src/route/rooms.js
> #39 simplify rooms api

- .gitignore
- app.js
- package.json
- src/db/mongo.js
- src/middleware/adminAuth.js
- src/route/admin.js
It closes #55 
AdminJS를 이용한 admin 페이지를 구현하였습니다.
isAdmin 속성(Boolean)이 true인 사용자만 `${backUrl}/admin`을 통해 접근할 수 있습니다.
- 채팅 연결하기(#25 머지 후)
> #55 implement admin page

- src/db/patterns.js
- src/middleware/validator.js
- src/route/admin.js
- src/route/auth.js
- src/route/auth.replace.js
- src/route/chats.js
- src/route/logininfo.js
- src/route/rooms.js
- src/route/static.js
- src/route/users.js
- src/service/rooms.js
- src/service/static.js
- src/service/users.js
> #75 Validation 방식 간소화

- package.json
It fixes #87 
test 환경에서 NODE_ENV가 설정되지 않는 문제를 해결합니다.
- 없음.
- 없음.
> Fix: Set NODE_ENV for test

- src/db/mongo.js
- src/route/admin.js
- src/route/chats.socket.js
- src/route/docs/chats.md
- src/service/rooms.js
It fixes #95 
방 생성자에 대한 입장 채팅 메시지가 생성되지 않는 문제를 해결합니다.
/rooms/create API에 대한 서비스 핸들러에 채팅 이벤트 발생 함수를 호출하도록 추가했습니다.
- 없음.
- 없음.
> #95 bug chat in msg not generated for creator

- .github/workflows/node.js.yml
- .gitignore
- package-lock.json
- package.json
- src/db/mongo.js
It closes #93 
GitHub Actions를 이용하여 taxi-back 레포지토리에 대한 CI를 활성화합니다.
메인 브랜치를 향하는 PR을 생성하면 자동으로 테스트를 수행하며, 테스트가 완료된 브랜치만 메인 브랜치에 병합할 수 있습니다.
S3 dev 버킷에 업로드한 DB 덤프 파일로부터 DB를 생성하는 것까지 완료하였습니다.
- 추가 예정(GitHub Actions 로그)
- taxi-front Github Action 작성
- 코드 커버리지 제약 추가
> #93 add ci

- src/service/chats.js
> #97 [Bug] Additional properties of "chatAfter" are not set properly

- src/modules/modifyProfile.js
- src/route/users.js
It closes #136 
공백 3개 입력 시 matches 되지 않아 400 error로 반환됨
-> error 세분화해서(?) front에 alert 해야할 것 같아요
> Refactor: handle space in nickname

- src/service/auth.replace.js
> Add: enter event listener 추가

- .github/pull_request_template.md
- .github/workflows/node.js.yml
> PR Template 수정

- src/service/rooms.v2.js
> #139 limit the number of rooms at searching request

- src/db/mongo.js
- src/route/users.js
- src/service/users.js
> Add: reportShcema

- app.js
- package-lock.json
- package.json
- src/middleware/limitRate.js
It closes #68 
https://www.npmjs.com/package/express-rate-limit
> Add: add rate limit middleware

- src/route/admin.js
It closes #148 
admin.js에 reportModel을 추가합니다.
추가하던 중 nginx 설정에 문제를 발견하여 수정하였습니다(노션 배포 문서에 반영되어 있음)
작동하는 모습.
필터링도 가능해요!
- Work on #149
> Add: reportModel to admin page

- app.js
- src/middleware/limitRate.js
> Fix: increase rate limit and exclude admin

- app.js
- src/route/docs/reports.md
- src/route/docs/rooms.v2.md
- src/route/reports.js
- src/route/users.js
- src/service/reports.js
- src/service/users.js
> #149 making report list api

- test/locations.js
> #154 locations.js 테스트 케이스 제작

- src/service/reports.js
It closes #166. 제가 잘 몰라서 일단 다른 파일의 코드들 참고해서 작동하는 대로 수정해봤습니다!
- 회의 때 얘기 나왔던 것 같은데 `reportSchema`에 `방 이름`이 없는 것 같습니다.
> #166 신고 내역 API 수정

- src/route/docs/rooms.v2.md
- src/route/rooms.v2.js
- src/service/rooms.v2.js
> #157 bug delete empty room

- src/db/patterns.js
- src/service/auth.js
It closes #178 
졸업생을 비롯한 여러 적격한 카이스트 구성원이 로그인할 수 없는 문제를 해결합니다.
없음.
없음.
- 다른 버그 해결 🏃
> #178 Bug: 졸업생 로그인 불가

- .github/workflows/node.js.yml
- .gitmodules
- package.json
taxiSampleGenerator repo를 submodule을 사용하여 taxi-back으로 이전시킵니다.
It closes #184 
> #184 taxiSampleGanerator 이전

- src/auth/login.js
- test/logininfo.js
> Refactor: extend session limit to 2 weeks

- src/db/mongo.js
- src/service/locations.js
> #183 locations sorting

- src/service/rooms.js
> #189 날짜범위 2주로

- .github/workflows/push_image_ecr.yml
- .github/workflows/push_image_ecr_dev.yml
- Dockerfile
- README.md
> #137.3 dev 브랜치로 머지시 ECR로 이미지 push

- src/db/mongo.js
- src/middleware/adminAuth.js
- src/route/admin.js
> #207 관리자 페이지 접속 IP 주소 제한

- app.js
- src/route/admin.logs.js
> #209 접속 기록(log)을 관리자가 볼 수 있도록 기능 추가

- src/service/rooms.js
It closes #190 
내 방 페이지의 방들이 정렬됨
> #190 [Bug] 내 방 리스트 API 검색에서 정렬 옵션 추가

- src/route/docs/auth.md
- src/service/auth.js
- src/service/auth.replace.js
It closes #191 
https://github.com/sparcs-kaist/taxi-front/pull/445
https://user-images.githubusercontent.com/69258815/213830439-0210f2a0-79fe-45a5-ba93-5ea8cb8c7c70.mov
> #191 logout api 호출 시 SSO 로그아웃URL 생성 및 전달

- src/service/auth.js
It closes #177 
로그아웃 시도에서 카이스트 구성원이 아닌 경우,
SSO 로그아웃 이후, 로그인 실패 URI 로 이동합니다.
https://user-images.githubusercontent.com/69258815/213908465-27f95075-4548-4c9c-9d55-62ab5b8ebce5.mov
> #177 [Bug] 카이스트 구성원이 아닌 경우 로그인 불가

- src/route/admin.logs.js
> #231 Admin.log 라우터 app crashed

- src/auth/login.js
> #241 자동 로그아웃 간격 1시간으로 수정

- src/route/notifications.js
> #248 Fix: notifications.js

- loadenv.js
It closes #256 
`loadenv.js`에서 `TEST_ACCOUNTS` 오타를 수정하였습니다.
> Fix: [Bug] loadenv `TEST_ACCOUNTS` 오타 수정

- src/routes/auth.js
- src/routes/auth.replace.js
- src/routes/rooms.js
- src/services/auth.js
- src/services/auth.replace.js
- src/services/rooms.js
It closes #264 
로그인, 로그아웃 API 에 입력 주소로 redirect 기능 추가
> #264 로그인, 로그아웃 API 에 입력 주소로 redirect 기능 추가

- src/modules/auths/login.js
It closes #188 
사용성 개선을 위해 로그인 만료 기간을 1시간에서 2주로 연장합니다.
- 없음.
> #188.2 로그인 만료 기간을 (다시) 2주로 연장

- app.js
- src/modules/patterns.js
> #265 방 이름 정규식에서 '~'를 비롯한 특수문자 허용

- src/modules/socket.js
> Fix: add populate in emitchatEvent

- src/modules/fcm.js
It closes #187 
웹, 안드로이드 기기 뿐만 아니라 IOS 앱에 FCM 알림 메시지 보냅니다.
> #187.2 IOS 앱에 FCM 알림 메시지 보내기

- src/modules/fcm.js
It closes #187 
웹, 안드로이드 기기 뿐만 아니라 IOS 앱에 FCM 알림 메시지 보냅니다.
> #187.3 IOS 앱에 FCM 알림 메시지 보내기

- app.js
- src/middlewares/information.js
- src/middlewares/originValidator.js
- src/services/auth.replace.js
It closes #316 
`docs`, `admin` 페이지는 `origin` 검사에서 제외시킵니다.
> #316.2 `docs`, `admin` 페이지는 `origin` 검사 제외

- src/modules/patterns.js
> #329 `/users/editAccount` API에서 빈 문자열 입력 허용

- app.js
- src/modules/stores/mongo.js
It closes #342 
mongo.js에서 스키마 선언 코드와 DB 연결 코드를 분리합니다.
이러면 다른 파일에서 스키마를 추가할 수 있습니다.
없음.
- 이벤트 스키마 작성.
> DB 시작 코드 분리

- src/lottery/index.js
- src/lottery/routes/docs/index.js
- src/lottery/routes/docs/items.js
- src/lottery/routes/docs/swaggerDocs.js
- src/lottery/routes/items.js
- src/lottery/services/items.js
- src/routes/docs/logininfo.js
It closes #336 
`/event/23-chuseok/item/list` API를 생성합니다.
추가한 이벤트 API 문서 (기존 문서 바로 아래에 보입니다).
- 그 다음으로 제일 빨리 할 수 있는 거
> #336 `/event/23-chuseok/items/list` API 생성

- app.js
- src/lottery/index.js
- src/lottery/routes/admin.js
> #348 `/event/23-chuseok/admin` 페이지 생성 

- src/lottery/index.js
- src/lottery/routes/docs/globalState.js
- src/lottery/routes/docs/swaggerDocs.js
- src/lottery/routes/globalState.js
- src/lottery/services/globalState.js
It closes #338 
/events/2023fall/global-state endpoint를 추가했고, 내부에서 사용할 수 있는 getUserCreditAmount 함수를 만들었습니다. 이 함수는 단순히 유저의 송편 개수를 반환할 뿐만이 아니라, 송편 개수를 업데이트 할 수 있는 메서드도 제공합니다.
- https://github.com/sparcs-kaist/taxi-back/issues/339
> #338 /event/23-chuseok/global-state 와 /event/23-chuseok/balance API 생성

- src/lottery/modules/credit.js
- src/lottery/routes/docs/items.js
- src/lottery/routes/items.js
- src/lottery/services/globalState.js
- src/lottery/services/items.js
It closes #339
/events/2023fall/items/purchase/:itemId API를 추가했습니다. random_box API는 외부로 노출하지 않고, 내부에 함수 형태로 구현하였습니다.
- https://github.com/sparcs-kaist/taxi-back/issues/340
> #339 /event/23-chuseok/items/purchase/:itemId 와 /event/23-chuseok/items/random_box API 생성

- src/lottery/index.js
- src/lottery/modules/admin.js
- src/lottery/modules/credit.js
- src/lottery/services/items.js
- src/modules/adminResource.js
- src/routes/admin.js
It closes #340 
routes/admin.js의 코드를 확장성 있도록 개선하고, 인스타그램 공유 보상을 관리자가 직접 지급할 수 있도록 해주는 custom action을 admin 페이지에 추가했습니다.
- 해당 custom action은 삭제되어야 합니다. (기획 변경)
> #340 `/event/23-chuseok/admin/credit_transfer` 와 `/event/23-chuseok/admin/credit_withdraw` API 생성

- src/lottery/modules/admin.js
- src/lottery/modules/populates/transactions.js
- src/lottery/modules/stores/mongo.js
- src/lottery/routes/docs/swaggerDocs.js
- src/lottery/routes/docs/transactions.js
- src/lottery/services/globalState.js
- src/lottery/services/items.js
- src/lottery/services/transactions.js
It closes #337
해당 API는 이미 기존 PR에서 구현되었습니다. 다만, Swagger를 사용한 문서화가 되지 않아 이번에 문서화를 진행하였습니다.
- Nothing
> #337 /event/23-chuseok/transactions API 생성

- src/lottery/modules/stores/mongo.js
- src/lottery/routes/docs/eventsSchema.js
- src/lottery/routes/docs/globalState.js
- src/lottery/routes/docs/items.js
- src/lottery/routes/docs/itemsSchema.js
- src/lottery/routes/docs/swaggerDocs.js
- src/lottery/routes/docs/transactions.js
It closes #362
eventSchema에 imageUrl 필드를 추가하였습니다. 이에 맞춰 Swagger 문서도 업데이트했습니다.
- Nothing
> #362 Event에 imageUrl 필드 추가

- src/lottery/index.js
- src/lottery/modules/stores/mongo.js
- src/lottery/routes/docs/publicNotice.js
- src/lottery/routes/docs/swaggerDocs.js
- src/lottery/routes/publicNotice.js
- src/lottery/services/globalState.js
- src/lottery/services/items.js
- src/lottery/services/publicNotice.js
It closes #366
에어팟 당첨 확률이 높은 상위 20명의 리더보드와, 그 리더보드에서 자신의 순위를 반환하는 Endpoint인 `events/2023fall/public-notice/leaderboard` 를 추가했습니다.
- 리더보드에 등록된 유저의 닉네임을 익명화하는 작업이 필요합니다.
> #366 응모권 리더보드 API 추가

- src/lottery/routes/docs/globalState.js
- src/lottery/routes/docs/globalStateSchema.js
- src/lottery/routes/docs/publicNotice.js
- src/lottery/routes/docs/quests.js
- src/lottery/routes/docs/swaggerDocs.js
- src/lottery/routes/globalState.js
- src/lottery/services/globalState.js
- src/modules/stores/mongo.js
It closes #377
이벤트 참여 동의시 유저에게 전화번호를 받아서 유저 스키마에 저장합니다.
> #377 이벤트 참여 동의시 전화번호 수집하여 저장

- src/lottery/modules/contracts/2023fall.js
It closes #341 
이벤트 퀘스트의 이름 및 설명을 수정하였습니다.
> #341.2 이벤트 퀘스트 이름 및 설명 수정

- loadenv.js
- src/lottery/modules/contracts/2023fall.js
- src/services/rooms.js
It closes #381
`loadenv.js` 에 있는 `eventConfig` 필드의 값을 하드코딩했습니다.
- Nothing
> #381 eventConfig 활성화

- src/lottery/services/publicNotice.js
It close #378
#378-public-notice-value-rank
public notice의 순위를 결정하는 가치 판단 함수
n
n
n
> #378 public notice API 개선

- src/lottery/services/publicNotice.js
It closes #407 
지금까지 사용하던 리더보드 확률 모델은 선형 모델과 지수 모델로 구성되어 있었는데, 선형 모델이 지수 모델보다 정확도가 떨어지는 것이 밝혀져, 선형 모델을 삭제하고 지수 모델만 사용하도록 변경했습니다.
https://sparcs.slack.com/archives/C01Q2FWE9H7/p1695743774361469
자세한 내용은 슬랙을 참고해 주시면 좋습니다.
전체 유저 수 124명, 전체 티켓 수 340개일 때 선형 모델과 지수 모델의 그래프입니다. x축은 특정 유저의 티켓 개수, y축은 특정 유저의 예측 상품 당첨 확률입니다. 파란색이 선형 모델, 빨간색이 지수 모델입니다. 실제 시뮬레이션 결과는 지수 모델과 더 가까웠으며, 선형 모델은 티켓 개수가 적을 때의 지수 모델의 근사치임을 위 그래프를 통해 확인할 수 있습니다.
- Nothing
> #407 리더보드 확률 모델 정확도 개선

- src/modules/stores/mongo.js
- src/routes/docs/logininfo.js
- src/services/logininfo.js
It closes #399 
`logininfo` API에 `phoneNumber`를 추가하였습니다.
> #399.1 `logininfo` API에 `phoneNumber` 추가

- .github/workflows/push_image_ecr.yml
- .github/workflows/push_image_ecr_dev.yml
It fixes #419 
자동 배포 GitHub Action에서 도커 이미지가 제대로 빌드되지 않는 문제를 (아마도) 해결합니다.
없음.
- 문제 발생 시 고치기 😨
> #419 [Bug] GitHub Actions에서 빌드한 이미지가 푸시되지 않음

- src/routes/docs/swaggerDocs.js
- src/routes/docs/users.js
- src/routes/users.js
- src/services/auth.js
- src/services/users.js
It closes #423 
users.js swagger  docs가 추가되었습니다.
> #423-set-nickname-and-profile-image-default

- src/modules/socket.js
> #270.2 socket update 오타 수정

- src/modules/patterns.js
> #453 학사 신입생 로그인 해결

- src/modules/slackNotification.js
- src/services/rooms.js
It closes #476
taxi-report-bot을 통해 전송되는 슬랙 알림 메세지를 수정하여 관리자가 필요한 정보를 더 빠르게 파악할 수 있도록 개선했습니다.
- Nothing
> #476 안티 어뷰징 시스템 개선

- src/modules/socket.js
It fixes #481 
세션이 만료될 때 서버가 비정상적으로 종료되는 문제를 해결합니다.
없음.
없음.
- 문제 발생 시 이슈 재오픈 필요.
> 세션 만료 시 Socket.io 연결 차단 

- src/views/loginReplacePage.js
> #486 [Bug] loginReplacePage 임시 수정

- src/modules/email.js
> #492 smtp nodemailer secure option turn off

- src/modules/email.js
It closes #492 
Testing with name (sparcs domain)
> #492 add name to nodemailer to resolve domain issue

- src/modules/email.js
Main branch update from Dev branch
> Main branch update from Dev branch

- loadenv.js
It closes #505 
이슈에서 언급한 바와 같이, 이벤트 코드를 비활성화하였습니다.
- Nothing
> #505 새터반 택시대제전 코드 비활성화

- src/modules/fcm.js
Fix problem with android notification not properly delivered
> hotfix: add android ttl payload to sendMessageByTopic function

- src/routes/docs/rooms.js
- src/services/rooms.js
It closes #517 
`rooms.js`에서 `checkIsAbusing`과 같이 handler에 보조적으로 사용되는 함수들은 밑으로 다 이동하였습니다.
> #517 미정산 시 방 생성/참여 차단

- src/routes/docs/rooms.js
- src/services/rooms.js
Reverts sparcs-kaist/taxi-back#521
> Revert "Revert "#517 미정산 시 방 생성/참여 차단""

- src/lottery/modules/contracts.js
- src/lottery/modules/quests.js
- src/lottery/routes/docs/globalState.js
- src/lottery/routes/docs/items.js
- src/lottery/services/items.js
It closes #540 
리더보드 순위 계산 방식을 제외한 모든 필요한 변경사항을 반영하였습니다. 순위 계산 방식 변경시 비효율성 발생&프론트 코드 수정이 필요하여 계산 방식은 현재 방식을 유지합니다.
- 필요하면 버그 수정
- 이벤트 코드 비활성화 (9/30 이후)
> #540 24 추석 이벤트 관련 마이너 변경사항

- src/index.ts
- src/loadenv.ts
- src/lottery/index.js
- src/lottery/middlewares/timestampValidator.js
- src/lottery/modules/contracts.js
- src/lottery/modules/quests.js
- src/lottery/modules/stores/mongo.js
- src/lottery/routes/docs/globalState.js
- src/lottery/routes/docs/invites.js
- src/lottery/routes/docs/items.js
- src/lottery/routes/docs/publicNotice.js
- src/lottery/routes/docs/quests.js
- src/lottery/routes/docs/swaggerDocs.js
- src/lottery/routes/docs/transactions.js
- src/lottery/routes/globalState.js
- src/lottery/routes/invites.js
- src/lottery/routes/items.js
- src/lottery/routes/quests.js
- src/lottery/routes/transactions.js
- src/lottery/schedules/detectAbusingUsers.js
- src/lottery/services/globalState.js
- src/lottery/services/invites.js
- src/lottery/services/items.js
- src/lottery/services/publicNotice.js
- src/routes/admin.js
- src/sampleGenerator/src/testData.js
- src/services/notifications.js
- src/services/rooms.js
- src/services/users.ts
이전 이벤트 코드를 활성화 했습니다.
env 파일에
EVENT_CONFIG={"mode":"default","period":{"startAt":"2025-02-08T18:25:53Z","endAt":"2025-02-15T18:25:53Z"}}
와 같이 임의로 이벤트 기간을 추가 작성해 실행할 수 있습니다.
> #563 이벤트 코드 활성화

- src/lottery/modules/contracts.js
- src/lottery/services/quizzes.ts
> #572 2025 봄 이벤트 퀘스트 업데이트 및 최종 검수

- src/lottery/services/items.js
It closes #580
내가 누구인지 userid를 통해 구분할 수 있게끔, 응답 정보에 userid를 추가하였습니다.
> #580 리더보드 나 아이콘 표시 문제

- src/loadenv.ts
- src/lottery/modules/quests.js
> #585 넙죽코인 소비를 위한 이벤트 기간 연장

- src/routes/docs/rooms.js
- src/routes/rooms.js
- src/services/rooms.js
It closes #599
routes/rooms.js 파일을 수정해서 rooms/searchByGap 엔드포인트를 추가한다.
> #599 유사 시간대 탑승자 방 추천 기능 구현

- src/services/notice.ts
> #615 [Bug] 공지사항 버그 수정
