sparcs-kaist/taxi-back

src/modules/logger.js
It closes #91 
winston의 file transport로써 사용되어서 매일 로그 파일을 새로 생성해주는 dailyRotateFileTransport 모듈에 인자로 넘긴 datePattern에 허용되지 않는 문자(":")가 있던 문제를 수정했습니다.
관련 이슈: https://github.com/winstonjs/winston-daily-rotate-file/issues/278
- 없음.
=> [Bug] Log file is not generated properly in Windows

app.js, src/db/patterns.js, src/route/docs/rooms.v2.md, src/route/rooms.js, src/route/rooms.v2.js, src/service/rooms.js, src/service/rooms.v2.js
It closes #101
백엔드에서 특정 API가 변경되었을 때 해당 API에 v2 태그를 붙여 기존 API가 계속 호환되도록 조치했습니다.
예를 들어, /rooms/create의 입력값이 바뀌었다면
- 입력값이 바뀐 새 API는 /rooms/v2/create
- 기존 API는 /rooms/create 를 통해 사용 가능합니다.
빠른 개발을 위해 기존 API는 프론트엔드의 main 브랜치에서 사용하지 않는 대로 바로 삭제하려고 합니다.
처음엔 location 스키마 변경에 영향을 받는 API의 수가 적을 거라고 생각해서 기존 API와 새 API를 한 파일에 작업했는데, 생각보다 바뀌어야 하는 API의 수가 많아서 기존 API와 새 API를 두 개의 파일로 분리하였습니다.
**기존 /rooms/search API 요청 결과**
**새 /rooms/v2/search API 요청 결과**
=> #101 create api versions

nodemon.json, package.json
It closes #104 
백엔드 서버의 시간대를 "Asia/Seoul"로 설정합니다.
이를 명시적으로 설정해야 하는 이유는 도커에서 Node 컨테이너를 생성할 때 기본 시간대가 UTC로 설정되어 있기 때문입니다.
Node는 process.env.TZ 환경변수에 설정된 시간대로 Date 객체의 기본 시간대를 결정하므로, TZ 환경변수를 서울로 설정하면 문제를 해결할 수 있습니다.
참조: https://www.ibm.com/docs/ko/cics-ts/5.6?topic=properties-setting-time-zone-nodejs-application
Timezone을 UTC로 설정한 다음 한국시간 기준 2022-08-12일 오전 4시 59분 20초에 서버를 실행한 모습
- 없음.
=> Add: set default timezone to Seoul

src/service/rooms.v2.js
It closes #109 
날짜만 검색조건에 주어졌을 때 쿼리 생성 중 24시간 이후(`maxTime`) 계산 방식을 변경했습니다.
- 기존: `getTomorrow5am` 함수 이용
- 이후: `Date.setTime` 이용
=> Fix: 24시간 후 계산하는 방식 변경

src/route/auth.replace.js
It closes #115 
auth.replace 라우터의 try(user 추가)에서 req.timestamp 속성을 사용하지만, 이를 설정해주는 setTimestamp 미들웨어를 호출하는 걸 빼먹은 문제를 수정합니다.
- 다양한 오류 수정
=> [Bug] auth.replace 유저 생성 안됨

src/route/chats.socket.js, src/service/rooms.v2.js
It fixes #113 
`src/route/chats.socket.js`에서 Promise constructor에 async 함수가 들어가는 패턴의 `chatsForRoom` 함수를 Promise constructor 없이 똑같은 기능을 하도록 수정하였습니다.
It fixes #114
Socket.io에서 사용자 session에 chatRoomId 속성을 설정해도 express의 session에 해당 값이 바로 저장되지 않는 문제가 발생하여, `session.save()`를 호출하여 명시적으로 Socket.io 세션과 express의 세션을 동기화했습니다.
- 수정 후, 브라우저에서 채팅방에 처음 들어갔을 때에도 사진이 잘 전송되었습니다. 수정한 코드를 주석 처리하면 문제가 다시 발생합니다.
- `/static` 라우터 제거: 서버에서 정적 파일을 호스팅할 필요가 없어졌습니다.
- 개발용 `/rooms`, `/users` API 제거: admin 페이지로 대체 가능합니다. https://github.com/sparcs-kaist/taxi-back/pull/100#discussion_r945340482
- **auth.replace 라우터 테스트케이스 고치기**: 로그인 시도 url이 `/auth/try`여야 하는데 테스트 코드에서는 `/auth/sparcssso`로 적혀 있어서 로그인 성공 여부가 …
=> #114 [bug] Express & Socket.io sessions are not synchronized automatically

src/db/mongo.js, src/route/chats.socket.js, src/route/docs/rooms.v2.md, src/route/rooms.v2.js, src/service/rooms.js, src/service/rooms.v2.js
It closes #119 
- 채팅 헤더의 "결제하기" 버튼을 눌렀을 때 해당 방의 정산 담당자를 해당 유저로 설정하는 기능을 구현했습니다.
- 프론트엔드에 전달되는 정산 상태를 `true | false`에서 `"not-departed" | "paid" | "send-required" | "sent"`로 변경했습니다.
- 1. `"not-departed"` :  아무도 결제/정산하지 않은 상태
- 2. `"paid"` : 택시비를 결제한 참가가 "결제하기" 버튼을 누르면 해당 참가자에게 설정되는 정산 상태.
- 3. `"send-required"` : 특정 참가자가 "결제하기" 버튼을 눌렀을 때 그 방의 나머지 참가자에게 설정되는 정산 상태.
- 4. `"sent"` : 정산 상태가`"send-required"`인 사용자가 "정산하기" 버튼을 눌렀을 때 그 사용자에게 설정되는 정산 상태.
그 외에도, `/rooms/edit`에서 참조하는 roomModel의 스키마를 고치던 중, `/rooms/edit`에서 두 문제를 발견하여 수정했습니다.
- 특정 방에 참여중이지 않은 사용자도 해당 방의 정보를 수정할 수 있음.
- 방의 최대 인원수(`maxPartLength`)를 현재 방에 참여중인 인원수보다 더 작게 설정할 수 있음.
- 없음.
- 안쓰는 API 제거하기 …
=> Add: update settlement schema and settlement APIs

src/service/auth.js
It fixes #128 
Auth.js 라우터를 사용했을 때, 회원가입 시 `ku_std_no`가 불러와지지 않는 문제를 해결합니다.
- 없음.
=> #128 bug sso ku std no not loaded

src/service/auth.js
Co-authored-by: 14KGun <geon6757@kaist.ac.kr>
It fixes #128 
`kaist_info`가 SSO로부터 주어지지 않을 때 JSON.parse 함수를 바로 사용할 수 없는 문제를 해결합니다.
- 없음.
=> Refactor: handle exception if kaist info is not provided

src/modules/modifyProfile.js, src/service/auth.js, src/service/logininfo.js, test/logininfo.js
It closes #132 
/json/loginInfo/detail API에서 사용자 이름을 반환합니다.
SPARCS SSO 로그인 시 사용자 이름을 자연스러워 보이게 변경합니다.  e.g.) `"JEONGSANG"` -> `"SANG JEONG"`
- Postman 결과
- 없음.
=> Include name in /json/loginInfo/detail

.dockerignore
It closes #137 
`.dockerignore`을 추가하여 local에서 도커 이미지 빌드 단계에사 `node_modules`, `.env`와 같은 파일들이 같이 `COPY`되는 것을 막습니다.
=> #137 dockerignore 추가

security.js, src/modules/fcm.js
It fixes #251
`security.aws.s3Url` 변수에 S3 버킷 이름 환경변수가 주입되지 않는 문제를 해결합니다.
It closes #252 
Flutter 기기에서 백그라운드 알림 수신이 가능하도록 알림 전송 시 메시지 페이로드에 `android` 옵션을 추가합니다.

기뻐서 우는 중
- FCM 해치웠나..?
=> #251 [Bug] AWS_S3_BUCKET_NAME not injected into security.aws.s3Url

src/modules/fcm.js
It closes #254 
기존 FCM message payload의 Notification에 담겨있던 title과 body를 data로 이동시킵니다 (android 앱과의 호환성 확보를 위해서입니다).
없음 (알림이 잘 동작하기 때문입니다 >.<)
- 없음.
=> #254 FCM 메시지 payload의 title과 body를 data로 이동

src/modules/fcm.js
It closes #176 
fcm 모듈에서
- `getTokensOfUsers` 함수가 notificationOptions 파라미터 검색을 하지 못하는 버그를 수정하였습니다.
- `registerDeviceToken` 함수에 "디바이스 토큰을 다른 사용자가 사용하고 있는지 확인 및 삭제" 기능을 추가하였습니다.
=> #176.2 fcm 모듈 버그

src/routes/docs/logininfo.js, src/routes/logininfo.js, src/routes/notifications.js, src/services/logininfo.js, src/services/notifications.js, test/logininfo.js
It closes #266 
1. 기존 session에 저장돼있는 deviceToken을 사용자가 /loginInfo/detail을 호출할 때 반환합니다.
2. notificationOption을 조회/수정할 때 사용자가 deviceToken을 보낼 필요 없이 기존 session의 deviceToken을 사용하도록 수정하였습니다.
-> 이를 통해 웹뷰 기반으로 구동되는 택시 앱 환경에서도 deviceToken 없이 마이페이지에서 알림 설정을 수정할 수 있습니다.
[TODO] Postman 스크린샷 추가
- 프론트 이슈 개설
=> #266 deviceToken & notificationOption 조회 및 수정 API 재정의

.eslintrc.js, src/modules/populates/rooms.js, src/routes/docs/rooms.md, src/routes/rooms.js, src/services/rooms.js, test/rooms.js
It closes #280 
로그인 없이도 (정산 정보를 제외한) 방 정보를 볼 수 있는 API를 작성합니다.
로그인 없이 접속할 수 있는 택시 공유 링크 클릭 시 방의 정보를 볼 수 있게 하기 위해서입니다.
(Postman에서 API 요청을 보낸 결과)
- https://github.com/sparcs-kaist/taxi-front/issues/544 해결
=> #280 로그인을 요구하지 않는 방 정보 반환 API 개발

src/modules/auths/login.js, src/modules/socket.js, src/services/chats.js, src/services/rooms.js
It closes #263
기존의 socketId 기반 socket 통신을 sessionId를 통해 구독으로 바꾸어 세션의 변경 없이 소켓 통신이 가능하도록 구조를 개편합니다.
taxi-front SocketToastProvider에서 health 관련 code 변경 시 제대로 작동합니다.
=> #263-채팅-socket-구조-개편

src/modules/socket.js
It closes #307 
계좌번호를 보낼 때 서버에서 각 기기로 알림을 전송하는 `emitChatEvent` 함수가 동작하지 않는 문제를 해결합니다.
채팅 type에 따라 알림의 본문(content)을 생성하는 `getMessageBody` 함수에서 정의되지 않은 type에 대해서는 `undefined`를 반환하기 때문에 문제가 발생했습니다.
- 없음.
=> [Bug] 계좌번호를 보낼 때 알림이 전송되지 않음

src/modules/stores/mongo.js
It closes #320 
권장 위도 경도 값
|위치|latitude|longitude|
|------|---|---|
|카이스트 본원|36.3723596|127.358697|
|대전역|36.3319731|127.4323382|
|갤러리아 타임월드|36.3517852|127.3787589|
|궁동 로데오거리|36.3606032|127.3500644|
|대전복합터미널|help?|help?|
|대전청사 고속버스터미널|36.3614807|127.3902714|
|대전청사 시외버스터미널|36.361552|127.3795484|
|만년중학교|help?|help?|
|서대전역|36.3227877|127.404696|
|신세계백화점|36.3744234|127.3820715|
|월평역|36.358475|127.363461|
|유성 고속버스터미널|36.3582923|127.3363614|
|유성 시외버스터미널|36.355613|127.334745|
DB 마이그레이션 이후 `latitude`, `longitude` 필드는 optional 에서 required 로 수정합니다.
=> #320 `/locations` API에 위도, 경도 추가

src/services/auth.js, src/services/auth.replace.js
It fixes #324, fixes #325 
1. 사용자가 서비스에 처음 로그인할 때 joinus 함수(sparcs sso로부터 받은 userData를 데이터베이스의 user collection에 저장함)에서 인자로 받지 않은 req의 timestamp 속성을 참조하는 것을 수정하였습니다.
2. SPARCS SSO(와 replace login)의 callback 핸들러에서 session의 loginAfterState 값에 대한 검증을 추가합니다. 
- 없음.
=> #324 [Bug] joinus 함수에서 req 인자가 누락되어 회원가입 불가, #325 [Bug] SPARCS SSO callback 핸들러에 임의로 접근한 경우 TypeError 발생

app.js, src/middlewares/errorHandler.js
It closes #326 
Uncaught exception을 처리하는 global error handler를 추가합니다.
기본 global error handler는 call stack을 클라이언트에 반환하기 때문에, 이를 반환하지 않는 global error handler를 추가하였습니다.
custom global error handler가 동작하는 모습입니다.
- error 로거 개선하기: Biseo에 수출한 것을 역수입해올 계획입니다.
=> #326 Global error handler 추가

loadenv.js, src/lottery/routes/docs/items.js, src/lottery/services/items.js
It closes #350
클라이언트에서 itemType에 따라 응모권과 응모권이 아닌 것을 구분해 렌더링하기 위해 itemType을 추가 반환합니다.
없음.
- 없음.
=> #350 `/events/2023fall/items/list`에서 itemType 반환

src/modules/logger.js
It closes #345 
택시에서 사용하는 winston 로거는 배열이 아닌 단일 객체를 입력받는 것을 기대하도록 구현되어 있기 때문에, 배열을 출력할 때 대괄호가 생략되는 오류가 발생합니다.
colorize 포맷을 사용할 때 {all: true} 옵션을 전달하여 배열을 출력하기 전 string으로 변환하도록 하였습니다.
이 외에도, 로컬 개발 시 unhandled exception이 파일로만 출력되던 것을 콘솔로 출력되게 바꾸었고, 로컬 개발 환경에서 파일로 로그가 출력되지 않게 변경하였습니다.
- Docker에서 로그 크기 제한하기 (https://docs.docker.com/config/containers/logging/local/#options)
=> #345 [Bug] logger에서 배열을 제대로 출력하지 않음

src/lottery/modules/admin.js, src/lottery/modules/credit.js, src/lottery/modules/stores/mongo.js, src/lottery/routes/docs/globalState.js, src/lottery/services/globalState.js, src/lottery/services/items.js, src/lottery/services/transactions.js
It closes #358 
It closes #335 
이제 `global-state` Endpoint에서 events 필드에 모든 이벤트의 목록을 담아 함께 전달합니다. 또, lottery 모듈의 db query를 수정하여 성능을 개선하였습니다. lean을 적극적으로 활용하고, TICKET 1, TICKET 2의 개수를 계산하는 알고리즘도 변경하였습니다.
- `global-notice` API 추가
=> #358 /events/2023fall/global-state API에서 이벤트 목록을 반환하도록 개선

src/lottery/modules/contracts/2023fall.js, src/lottery/modules/quests.js, src/lottery/routes/docs/globalState.js, src/lottery/routes/docs/itemsSchema.js, src/lottery/routes/globalState.js, src/lottery/routes/items.js, src/lottery/services/globalState.js, src/lottery/services/items.js, src/services/notifications.js, src/services/rooms.js, src/services/users.js
It closes #372 
새롭게 추가된 `/global-state/create` API를 통해 eventStatus를 생성할 수 있습니다.
- eventStatus가 생성되면 자동으로 firstLoginQuest가 완료되고 보상이 지급됩니다.
- eventStatus가 생성되기 전 `/items/purchase/:itemId` API를 호출하면 400 BAD REQUEST 오류가 발생합니다. 오류 메시지: `Items/Purchase : nonexistent eventStatus`
- `completeQuest` 함수에서는 eventStatus가 존재하지 않는 경우 아무 로그도 남기지 않고 종료됩니다.
- #365
=> #372 이벤트 참여 동의 여부 확인

src/lottery/middlewares/timestampValidator.js, src/lottery/routes/docs/quests.js, src/lottery/routes/globalState.js, src/lottery/routes/items.js, src/lottery/routes/quests.js, src/lottery/services/globalState.js, src/lottery/services/items.js, src/lottery/services/publicNotice.js, src/lottery/services/quests.js
It closes #383 
`/events/2023fall/global-state/create` , `/events/2023fall/quests/instagram/share-event` , `/events/2023fall/quests/instagram/share-purchase` 3개의 Endpoint에 이벤트 기간 전에 HTTP Request를 요청할 경우, 400 BAD REQUEST 오류를 발생시키도록 변경했습니다.
- Nothing
=> #383 `/global-state/create` Endpoint에 이벤트 기간에만 접근 가능하도록 변경

src/lottery/modules/quests.js, src/lottery/routes/docs/itemsSchema.js, src/lottery/services/items.js, src/lottery/services/publicNotice.js, src/lottery/services/transactions.js
It closes #387 
- 랜덤박스에서 아이템을 뽑는데 실패한 경우, 유저의 상태를 랜덤박스 구입 이전으로 복원하도록 개선했습니다.
- 아이템 재고가 없을 때 항상 400 BAD REQUEST를 전송하도록 변경했습니다.
- 아이템의 `stock` 필드는 0 또는 1로만 반환됩니다. 타입은 여전히 `number` 입니다.
- 0은 재고가 없는 경우, 1은 재고가 있는 경우입니다.
- 반영된 곳: `/events/2023fall/items/list` , `/events/2023fall/items/purchase/:itemId` , `/events/2023fall/transactions`
- Nothing
=> #387 아이템 관련 API 개선

src/lottery/index.js, src/lottery/modules/items.js, src/modules/adminResource.js
It closes #389
adminJS의 Item Resource에 addOneItemStock 및 addFiveItemStock Record Action이 추가되었습니다. 각각 안전하게 아이템의 재고를 1개, 5개씩 추가하는 Action입니다.
현재 각 Action에 대한 HTTP Request가 `GET` 으로 전송되고 있습니다. `POST` 로 전송하는 법을 아시는 분은 알려주시면 감사하겠습니다..!
- Nothing
=> #389 adminJS에 아이템 재고 추가 Action 추가

src/lottery/modules/contracts/2023fall.js, src/lottery/modules/populates/transactions.js, src/lottery/modules/quests.js, src/lottery/modules/stores/mongo.js, src/lottery/routes/docs/globalState.js, src/lottery/routes/docs/items.js, src/lottery/routes/docs/itemsSchema.js, src/lottery/routes/docs/quests.js, src/lottery/routes/docs/questsSchema.js, src/lottery/routes/docs/swaggerDocs.js, src/lottery/routes/quests.js, src/lottery/services/items.js, src/lottery/services/quests.js
It closes #391
`/events/2023fall/quests` 라우터 아래에 있던 다양한 퀘스트 완료 요청 API를 `/events/2023fall/quests/complete/:questId` API로 통합하였습니다. 또, itemSchema에 instagramStoryStickerImageUrl 필드를 추가했습니다.
- Nothing
=> #391 방 공유 퀘스트 완료 API 추가

app.js, src/middlewares/limitRate.js
It fixes #396 
Express의 trust proxy 설정이 꺼져 있어, 모든 사용자에 대해 동일한 기준으로 rate limit이 걸리는 현상이 발생했습니다.
모든 IP의 proxy를 신뢰하는 설정을 추가하였습니다(https://expressjs.com/en/guide/behind-proxies.html 참조).
없음.
- 없음.
=> [Bug] trust proxy 설정

src/lottery/modules/contracts/2023fall.js
It closes #400 
paying, sending, payingAndSending 퀘스트의 완료 조건에 **택시 출발 시각**을 추가하였습니다. 택시 출발 시각이 이벤트 기간 내에 포함되어야만 퀘스트가 완료됩니다. 추가로, 위의 3가지 퀘스트가 완료되는 경우 어떤 방에서 정산/송금 요청이 발생했는지 로그에 기록하도록 개선했습니다.
- #399
=> #400 정산 및 송금 요청 관련 퀘스트 달성 조건 변경

src/lottery/middlewares/checkBanned.js, src/lottery/routes/docs/globalState.js, src/lottery/routes/docs/items.js, src/lottery/routes/docs/quests.js, src/lottery/services/items.js
It closes #405 
checkBanned 미들웨어를 사용하면, req 객체에 eventStatus를 메모이제이션 하기 때문에 다시 검색할 필요가 없어 검색 쿼리가 줄어듭니다.
JSDocs와 swaggerDocs에 설명 및 400에러에 대한 설명을 적었습니다.
n
n
=> #405 reduction in eventStatus query

loadenv.js
It closes #416 
추석 이벤트 기간을 11일 수요일 23시 59분까지로 연장했습니다.
- `loadenv.js` 의 `eventConfig` 를 `undefined` 로 변경 (이벤트 종료 후)
=> #416 추석 이벤트 기간 연장

loadenv.js
It closes #421
`eventConfig` 의 기본값을 삭제하여, 추석 이벤트 관련 라우터가 동작하지 않도록 했습니다.
- Nothing
=> #421 추석 이벤트 관련 코드 비활성화

src/routes/docs/swaggerDocs.js
It closes #426 
swagger에서 `servers` option을 사용하여 request를 보내고 싶은 base url을 설정 가능합니다.
- development 환경에서는 `http://localhost:port`, `main 서버`, `dev 서버`에 대해 모두 테스트 가능하고,
- production 환경에서는 `main 서버`에 대해서만 테스트 가능하도록 변경하였습니다.
=> #426 [Bug] Swagger api 테스트가 작동하지 않음

app.js
It fixes #433 
reverse proxy 서버가 2대이므로 trust proxy 값이 2로 설정되어야 합니다.
없음
- 없음.
=> #433 [Bug] trust proxy 값이 잘못 설정됨

src/routes/docs/rooms.js, src/services/rooms.js
It closes #441
간단하게 request의 timestamp와 출발 시각을 비교하여, timestamp가 출발 시각 이후인 경우 error를 반환합니다.
아래를 보시면 1:30 이후에 방 생성을 잘 막아주는 걸 알 수 있습니다.
=> #441 방 생성 시각의 유효성을 검사하지 않는 버그

src/routes/docs/utils.js
It fixes #463 
ObjectId 검증 시 사용하는 정규식에 있는 오타를 수정합니다.
(현재) `` `^[a-fA-F\d]{24}$` ``
(수정) `` `^[a-fA-F\\d]{24}$` `` (백슬래시 이스케이프 문제)
**현재 ajv의 validateBody 함수로 `"/reports/create"` API의 입력값을 검증할 때 `objectIdPattern`을 사용하기 때문에, 정상적인 피신고자의 ObjectId(reportedId)가 입력값 검증을 통과하지 못합니다.**
참고로 다른 API에서는 아직 `objectIdPattern`을 바탕으로 입력값을 검증하지 않아서, 신고 생성 시에만 문제가 발생하고 있습니다.
없음.
- 정규식 수정 이후 신고 생성 스크린샷
- 없음.
=> #463 [Bug] ObjectId 검증 정규식 오타 수정

src/lottery/index.js, src/lottery/modules/contracts.js, src/lottery/modules/quests.js, src/lottery/modules/stores/mongo.js, src/lottery/routes/docs/invite.js, src/lottery/routes/docs/inviteSchema.js, src/lottery/routes/docs/quests.js, src/lottery/routes/docs/questsSchema.js, src/lottery/routes/docs/swaggerDocs.js, src/lottery/routes/invite.js, src/lottery/services/globalState.js, src/lottery/services/invite.js
It closes #457 
추천인 시스템을 구현하기 위해, 초대 링크 관련 API를 구현합니다.
- #467
=> #457 추천인 시스템 구현

src/lottery/index.js, src/lottery/modules/slackNotification.js, src/lottery/schedules/detectAbusingUsers.js, src/lottery/schedules/index.js, src/modules/slackNotification.js, src/routes/rooms.js, src/services/reports.js, src/services/rooms.js
It closes #467 
지난 가을학기 때 발생했던 어뷰징 사례를 기반으로, 예상되는 어뷰징 유형을 자동으로 탐지하고 대응 과정을 간편하게 만듭니다.
- Nothing
=> #467 어뷰징 대응 자동화

src/lottery/modules/contracts.js, src/lottery/services/globalState.js
It closes #474 
이슈에서 언급한대로, 추천인 퀘스트에 대한 설명을 보강하여 사용자들이 쉽게 이해할 수 있도록 개선했습니다. 부가적으로, globalState API에서 관리자의 경우 isEligible 필드를 항상 true를 설정하도록 하여 production 환경에서도 주요 기능을 테스트할 수 있도록 합니다. (단, 이벤트 참여는 불가능합니다.)
- Nothing
=> #474 추천인 퀘스트 설명 업데이트

src/lottery/schedules/detectAbusingUsers.js
It closes #479 
새벽 4시마다 작동하는 어뷰징 감지 스크립트에서, 기준 3: "채팅 개수가 5개 미만인 방"의 조건을 잘못 설정하여, 혼자 참여한 방이어도 채팅 개수가 5개 미만이면 어뷰징으로 인식하는 버그가 있었습니다. 이를 이 PR에서 수정하였습니다.
- Nothing
=> #479 [Bug] 참여자가 1명인 방에 대해서도 어뷰징 감지 스크립트가 반응하는 버그

loadenv.js, package.json, pnpm-lock.yaml, src/modules/email.js, src/modules/stores/aws.js, src/services/reports.js
It closes #461
기존에 AWS SES([taxi.sparcs@gmail.com](mailto:taxi.sparcs@gmail.com) 계정)로 전송하는 신고 메일을 SMTP 방식([taxi@sparcs.org](mailto:taxi@sparcs.org))으로 전송하도록 수정합니다.
production 환경에서는 gmail로 이메일을 전송하고, development나 test 환경에서는 [Ethereal](https://ethereal.email/) 서비스를 사용해 mock 이메일을 전송합니다([nodemailer 문서 - Testing SMTP](https://nodemailer.com/smtp/testing/)).
@DoyunShin 도움 주셔서 감사드립니다.. ❤️ 
없음.
- mock 이메일이 Ethereal 서버로 전송되면, 이메일 미리보기 url이 로그로 기록됩니다.
- Ethereal 서비스를 사용한 mock 이메일 예시입니다.
- 없음.
=> #461 메일 전송 SMTP으로 변경

src/lottery/modules/slackNotification.js, src/lottery/schedules/detectAbusingUsers.js
It closes #489 
새벽 4시마다 작동하는 어뷰징 감지 스크립트에서, 기준 2: "하루에 탑승 기록이 많은 사용자"의 조건을 잘못 설정하여, 이벤트에 참여하지 않았더라도, '이벤트 참여자와 함께' 하루에 2번 이상 탑승하면 어뷰징으로 인식하는 버그가 있었습니다. 이를 이 PR에서 수정하였습니다.
- Nothing
=> #489 [Bug] 이벤트에 참여하지 않은 사용자에 대해서도 어뷰징 감지 스크립트가 반응하는 버그

src/modules/email.js
It closes #499
인증서 관련해서 알 수 없는 이유로 발생하는 SSL 오류로 인해 메일 전송이 안되는 이슈가 있었고, 이 PR에서 해당 현상을 임시적으로 수정하였습니다.
=> #499 [Bug] 메일 전송 안됨

src/modules/fcm.js
FCM 메세지가 안드로이드 특정버전에서 앱을 종료했을 때 오지 않는 이슈 해결
=> hotfix: add android payload to fcm send message

src/services/auth.js
=> #514 랜덤 이메일 업데이트

src/modules/stores/mongo.js, src/routes/admin.js, src/routes/docs/users.js, src/routes/users.js, src/services/users.js
It closes #516 
`ban` 관련 모든 api는 `/users` router의 하위 api로 동작합니다.
- `/users/isBanned`
- `/users/getBanRecord`
=> #516 blockedlist

src/routes/docs/rooms.js, src/services/rooms.js
Reverts sparcs-kaist/taxi-back#518
=> Revert "#517 미정산 시 방 생성/참여 차단"

src/modules/patterns.js, src/routes/chats.js, src/routes/docs/schemas/chatsSchema.js, src/routes/docs/swaggerDocs.js
It closes #449 
채팅이 공백이 아닌 문자 하나 이상을 포함 해야만 validate 하도록 정규 표현식을 추가해주었습니다. (patterns.js 참고)
*현재대로라면 빈 문자열을 보낼 시 오류 페이지로 넘어가서 프론트 작업 확인 후 머지되어야 합니다!!
관련 front issue: https://github.com/sparcs-kaist/taxi-front/pull/777
[Front] 해당 패턴을 사용시 전송 버튼 disable로 변경 및 해당 validation 오류(400) 대처할 수 있어야 함.
=> #449-2 채팅 빈 문자열 검증

src/modules/fare.js, src/services/fare.js
It closes #534 
Credentials가 존재하지 않을 때 503 에러를 제대로 반환합니다.
- Nothing
=> #534 [Bug] 네이버 지도 API Credentials가 존재하지 않을 때의 잘못된 동작

src/lottery/routes/docs/items.js, src/lottery/routes/docs/schemas/itemsSchema.js, src/lottery/routes/items.js, src/lottery/services/items.js
=>  feat: add item handler

package.json, pnpm-lock.yaml, src/modules/fcm.js
It closes #547 
FCM 푸시 알림이 수신되지 않는 것처럼 보이던 버그를 수정합니다.
- Deprecated된 API를 사용하고 있었어서, 간헐적으로 FCM 전송이 실패하던 문제가 있었습니다.
- 기본 아이콘이 잘못된 URL을 가지고 있어, 사용자의 휴대폰까지 FCM이 전송되었지만 알림이 표시되지 않던 문제가 있었습니다.
- `firebase-admin` 패키지의 버전도 major 버전이 바뀌지 않는 선에서 최대한 업데이트했습니다.
- 수신 실패한 디바이스 토큰을 삭제하는 코드에 버그가 있어 수정이 필요합니다.
=> #547 [Bug] FCM 푸시 알림이 수신되지 않는 버그

src/modules/fcm.js
It closes #550
FCM 푸시 알림이 안드로이드 기기에서 가끔 수신되지 않던 버그를 수정합니다.
high priority는 사용을 자제하는 것이 좋으나, 채팅의 경우에는 우선순위가 높다고 판단하여 일단 사용하기로 결정하였습니다. 필요한 경우 차후 논의를 거친 후 수정해도 좋을 것 같습니다.
- #548 에서 언급했듯이, 수신 실패한 디바이스 토큰을 삭제하는 코드에 버그가 있어 수정이 필요합니다.
=> #550 [Bug] FCM 푸시 알림이 수신되지 않는 버그 2

Dockerfile
It closes #558
TypeScript에 맞춰서, 빌드를 한 후 실행하도록 Dockerfile을 수정하였습니다. 이미지 용량을 줄이기 위해 2 Stage Build를 도입하였습니다.
=> #558 [Bug] Dockerfile이 올바르지 않음

src/lottery/middlewares/checkBanned.js, src/lottery/modules/contracts.js, src/lottery/modules/items.js, src/lottery/modules/quests.js, src/lottery/modules/slackNotification.js, src/lottery/modules/stores/mongo.js, src/lottery/routes/docs/items.js, src/lottery/routes/docs/schemas/itemsSchema.js, src/lottery/routes/items.js, src/lottery/routes/publicNotice.js, src/lottery/schedules/detectAbusingUsers.js, src/lottery/services/globalState.js, src/lottery/services/invites.js, src/lottery/services/items.js, src/lottery/services/publicNotice.js, src/lottery/services/quests.js, src/lottery/services/transactions.js, src/schedules/deleteUserInfo.js, src/services/users.ts
It closes #570
`POST /events/2025spring/items/useCoupon/:couponCode` Endpoint를 사용해 쿠폰을 사용할 수 있습니다. 쿠폰 코드는 알파벳 대소문자 및 숫자로만 구성될 수 있습니다. 각각의 쿠폰은 사용자마다 최대 1회만 사용될 수 있습니다.
추가로, 이벤트에 참여한 회원의 경우 탈퇴를 제한하도록 조치하였습니다.
=> #570 2025 봄 이벤트 쿠폰 기능 추가

src/loadenv.ts, src/lottery/modules/contracts.js, src/lottery/modules/quests.js, src/lottery/services/globalState.js
다단계 시스템을 추가했습니다
It closes #573
=> #573 2025 봄 이벤트 간접 초대 기능 추가

src/services/auth.js
It closes #577 
Production 환경에서, SPARCS SSO에서 돌아온 후 로그인을 거부하는 이유가 2가지가 있습니다.
- 카이스트 구성원이 아닌 경우
- 콜백으로 돌아오기 전/후의 세션이 다른 경우
위와 같은 경우 로그인 실패 페이지로 리다이렉트를 시키는데, 원인을 로그에 기록하도록 개선하였습니다. 특히, 카이스트 구성원이 아니여서 로그인을 거부하는 경우, UID, SID, 학번, 구성원 타입을 로그에 남기도록 하여 CS에 참고할 수 있도록 하였습니다.
=> #577 로그인 거부시 거부 사유를 로그에 기록

src/modules/populates/rooms.ts
It closes #618 
`room/search` API에서 location을 표현 할 때, 좌표값을 포함합니다.
=> #618 방 검색에 위치 좌표 추가
